### ISSUE TITLE
Found on any.run

### ISSUE THREAD

**Issue by thedudefello** [N17Pro3426/TrashMade#7]
**Hi**, I'm not sure if you can request to upload malware to here, but I found this...
https://app.any.run/tasks/8cf901b3-ac5f-4658-a1a1-d3d237903173/

**Comment by thedudefello** [comment]
[OnePieceOfTape.zip](https://github.com/user-attachments/files/16318870/OnePieceOfTape.zip)
Password is "infected"

**Comment by N17Pro3426** [comment]
also who made it?

**Comment by thedudefello** [comment]
I'm not sure. At least it's kinda original. But that's my opinion.

**Comment by N17Pro3426** [comment]
I asked who created it

**Comment by thedudefello** [comment]
I don't know.

**Comment by N17Pro3426** [comment]
ok
